apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: cloud-alerts
  namespace: cloud-boilerplate
spec:
  groups:
  - name: cloud-monitoring.rules
    rules:
    - alert: HighErrorRate
      expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.05
      for: 2m
      labels:
        severity: critical
      annotations:
        summary: "API High Error Rate detected"
        description: "More than 5% of requests are failing."

    - alert: StalledWorker
      expr: time() - worker_last_update_timestamp_seconds > 300
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Worker is stalled"
        description: "Worker hasn't updated the timestamp in 5 minutes."

    - alert: PodCrashLooping
      expr: rate(kube_pod_container_status_restarts_total[5m]) > 0
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "Pod is crash looping"