apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-worker
  namespace: cloud-boilerplate
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: cloud-worker
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cloud-worker
    spec:
      imagePullSecrets:
        - name: ghcr-secret

      terminationGracePeriodSeconds: 30
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
      containers:
        - name: worker
          image: ghcr.io/pokomiko/cloud-native-boilerplate-worker:latest
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          env:
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: APP_ENV
            - name: WORKER_INTERVAL_SECONDS
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: WORKER_INTERVAL_SECONDS
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - test -d /proc/1
            initialDelaySeconds: 20
            periodSeconds: 30
